import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import "./globals.css";

import StoreProvider from "./StoreProvider";
import ConvexClientProvider from "./ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "דיאטה AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClientProvider>
      <html lang="en" dir="rtl" data-theme="dark">
        <body className={inter.className}>
          <StoreProvider>
            <NavBar /> {children}
          </StoreProvider>
        </body>
      </html>
    </ConvexClientProvider>
  );
}
