import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import ConvexClientProvider from "./ConvexClientProvider";
import Res from "@/components/NavBar/Res";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "דיאטה AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;

  const messages = await getMessages();
  console.log(locale);
  return (
    <NextIntlClientProvider messages={messages}>
      <ConvexClientProvider leng={locale}>
        <html
          lang={locale}
          dir={locale === "he" ? "rlt" : "ltr"}
          data-theme="dark"
          className="page"
        >
          <body className={inter.className + "relative"}>
            <NavBar />

            {children}
          </body>
        </html>
      </ConvexClientProvider>
    </NextIntlClientProvider>
  );
}
